import Link from 'next/link';
import './globals.css';

export const metadata = {
  title: 'My first Next App',
  description: 'Generated by create next app',
  keywords:'next,react,app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <h1>Navegación</h1>
        <ul>
          <li>
              <Link href='/'>Home</Link>
          </li>
        </ul>
        <ul>
          <li>
            <Link href='/about'>About</Link>
          </li>
        </ul>
        <ul>
          <li>
            <Link href='/services'>Services</Link>
          </li>
        </ul>
        
        {children}</body>
    </html>
  )
}
