import Link from 'next/link';
/*Ruta absoluta */
import Navigation from "@/components/Navigation"
import './globals.css';

export const metadata = {
  title: 'My first Next App',
  description: 'Generated by create next app',
  keywords:'next,react,app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es_mx">
      <body>
    
        <Navigation/>
        {children}</body>
    </html>
  )
}
